### ISSUE TITLE
[Provider] Add support for Huggingface inference endpoints

### ISSUE THREAD

**Issue by vrushankportkey** [Portkey-AI/gateway#11]
Docs: https://huggingface.co/docs/api-inference/quicktour

**Comment by rayaanoidPrime** [comment]
Hey is this issue open? Would love to take it on.

**Comment by roh26it** [comment]
Yes, would love to review a PR on this!

**Comment by MuraraAllan** [comment]
Do they still give away those shirts for hacktoberfest? 
I still have the blue one from 2017 lol 

If still for grab I would like to tackle this one

**Comment by vrushankportkey** [comment]
haha, not sure actually! but would love to have some contributions for this one!

**Comment by MuraraAllan** [comment]
let's build it \o/
