### ISSUE TITLE
[Provider] Add Deepinfra 

### ISSUE THREAD

**Issue by vrushankportkey** [Portkey-AI/gateway#110]
Docs: https://deepinfra.com/docs

**Comment by Suraj-Bhandarkar-S** [comment]
Hello, if this is available can I take a look at this? its something new for me but want to give it a try :).

**Comment by vrushankportkey** [comment]
Hi @Suraj-Bhandarkar-S yes, this is an open issue that you can work on. Thank you so much for contributing to the project!

**Comment by vidurkhanal** [comment]
@vrushankportkey @Suraj-Bhandarkar-S mind if I give it a try as well?

**Comment by vrushankportkey** [comment]
Please feel free to collaborate/contribute. I think as the project grows, the best practices on this should emerge. I'd suggest to use [this thread](https://discord.com/channels/1143393887742861333/1195071847260233808/1195071855732740106) to collaborate.

**Comment by Suraj-Bhandarkar-S** [comment]
@vidurkhanal Thank you :) I have started to work, will try if any thing will post in the thread. Thanks again

**Comment by vidurkhanal** [comment]
@vrushankportkey could you resend the discord invite? The link you sent might have expired.

**Comment by VisargD** [comment]
Hey folks. Just checking up on this. Please let me know if there are any blockers that you are facing.

**Comment by vidurkhanal** [comment]
Hey @VisargD, as of today the only service offered by deepinfra is inference (emitting a models output as it is). The confusion is which action would it fall under. Would it be chat or embed!?

**Comment by VisargD** [comment]
Deepinfra has an OpenAI compatible API: https://deepinfra.com/docs/advanced/openai_api

You can simply map this API with /chat/completions route of gateway
