### ISSUE TITLE
Support for Speech-to-Text (STT) or Text-to-Speech (TTS) APIs?

### ISSUE THREAD

**Issue by davidmyersdev** [Portkey-AI/gateway#125]
Do you plan to support STT or TTS (audio) APIs as well, or is that outside the scope of this project?

**Comment by ralyodio** [comment]
i'm also interested in this.

**Comment by VisargD** [comment]
Gateway currently supports these routes already. They are not a part of unified interface yet as we have not seen requests apart from OpenAI. But these routes should work as a proxy. Here is an example for OpenAI transcription and TTS APIs.

Transcription:
```
curl --location 'http://localhost:8787/v1/audio/transcriptions' \
--header 'Authorization: Bearer <openai-api-key>' \
--header 'x-portkey-provider: openai' \
--form 'file=@"file"' \
--form 'model="whisper-1"'
```

TTS:
```
curl --location 'http://localhost:8787/v1/audio/speech' \
--header 'Authorization: Bearer <openai-api-key>' \
--header 'x-portkey-provider: openai' \
--header 'Content-Type: application/json' \
--data '{
    "model": "tts-1",
    "input": "The quick brown fox jumped over the lazy dog.",
    "voice": "alloy"
  }'
  ```
  We are open to build unified route for these APIs if people are using other providers apart from OpenAI. But you can always use the above format to hit the OpenAI TTS and STT APIs. Please let me know if you need any other help with this.

**Comment by ralyodio** [comment]
what about using open source models for stt and tts?

**Comment by roh26it** [comment]
Which STT and TTS models are you using and on which providers?

**Comment by ranjancse26** [comment]
@roh26it Please take a look into [assemblyai](https://www.assemblyai.com/). They are popular in the audio intelligence. Hope to have the support for the same.

**Comment by vrushankportkey** [comment]
Closing this issue - please feel free to raise separate issue for Provider integrations specific to STT or TTS!
