### ISSUE TITLE
[Docs] How to deploy on AWS Lambda

### ISSUE THREAD

**Issue by codeyourwayup** [Portkey-AI/gateway#128]
Please write a short tutorial, thanks.

**Comment by VisargD** [comment]
We will surely add a documentation for that. But till that is live, you can go through this documentation and make changes to your forked copy of gateway.
https://hono.dev/getting-started/aws-lambda

Gateway internally uses hono.dev framework. So all of their setup guides should also work for this repo. Please let me know if you face any issues with this.

**Comment by VisargD** [comment]
Hey. Was this helpful. Were you able to deploy on AWS Lambda?

**Comment by vrushankportkey** [comment]
Closing the issue since it's been a long enough time.
