### ISSUE TITLE
Dall-E 2 and other images providers?

### ISSUE THREAD

**Issue by alexander-potemkin** [Portkey-AI/gateway#130]
Hello and thank you for the software! Do you have any plans to add support for the images providers? Dall-E 2 to start with? :)

**Comment by VisargD** [comment]
Gateway currently supports images routes already. Here is an example for OpenAI image generations API

```
curl --location 'http://localhost:8787/v1/images/generations' \
--header 'Content-Type: application/json' \
--header 'x-portkey-provider: openai' \
--header 'Authorization: Bearer <openai-key>' \
--data '{
    "model": "dall-e-3",
    "prompt": "A cute baby sea otter",
    "n": 1,
    "size": "1024x1024"
  }'
```

Please let me know if you need any help with this.

**Comment by alexander-potemkin** [comment]
@VisargD , thank you!

Any plans to add other providers? Or offer framework to add them, like extensions or something of the kind?

**Comment by VisargD** [comment]
What other providers are you currently using?

**Comment by alexander-potemkin** [comment]
I'd like to use Midjourney and StableDiffusion; ideally - HuggingFace providers as well.

**Comment by vrushankportkey** [comment]
Thanks, @alexander-potemkin - added two new issues to track this: #153 & #152

**Comment by alexander-potemkin** [comment]
Thank you! Any plans for kind of extensions?

**Comment by vrushankportkey** [comment]
Good idea! We've previously discussed developing something like "plugins" that connect to the gateway - this can enable connections to other middleware tools or evals tools like [Ragas](https://github.com/explodinggradients/ragas). 

Extensions/frameworks to add provider would also be cool. So far I think our experience has been that it takes a good amount of work to make different APIs compatible with the OpenAI signature — it requires trade offs and on-the-fly decisions. Sometimes, everything can be the same but the error handling might be different! 

So at least right now, we're looking separately at each new provider that has to be added. But happy to explore which common framework could emerge.

**Comment by mike-reynolds-personal** [comment]
I would 2nd the plugins methodology. We are specifically looking at how different LLMs could be hosted on-prem and then use Portkey to proxy calls between on-prem or on-cloud providers (if that makes sense).

Even an initial guide of how to extend Portkey with 'custom' providers, or how one would wrap an LLM service to provide OpenAI spec based request and response. If we did this, then presumably we could simply create a new Portkey provider that accepted a service URL within the config header...

**Comment by vrushankportkey** [comment]
Makes sense, @mike-reynolds-savient! Thank you for sharing. Would love to understand what you're using to run the LLMs on-prem.

We just discussed this here as well: #124

**Comment by mike-reynolds-personal** [comment]
> Makes sense, @mike-reynolds-savient! Thank you for sharing. Would love to understand what you're using to run the LLMs on-prem.
> 
> We just discussed this here as well: #124

Our 'generate embeddings' feature is in active design/ development, but to date we have used LLMs and M/L services wrapped using [FastAPI](https://fastapi.tiangolo.com/), although there is no spec for the request/response.

#124 Looks good - If the openAPI provider is essentially providing the translation layer then my 2nd thought above would be completely workable with the addition of the base_url.
