### ISSUE TITLE
Decouple Prompt Management with the Provider

### ISSUE THREAD

**Issue by ranjancse26** [Portkey-AI/gateway#133]
Ideally, the prompt library management should work in a highly generic manner with no dependency on the LLM provider. Sorry if I am confused or missing anything. At the moment, I see the prompt creation is directly tied to the LLM Provider and model. This is a huge problem as the consumers won't be able to reuse the prompt template and run it against the preferred LLM provider.

**Comment by VisargD** [comment]
Hi @ranjancse26 - Currently, once a prompt is saved on the platform, we do not allow changing the provider. The  workaround for this is to create a copy of the prompt using the duplicate button that is present on the prompt list screen. This will take you the prompt playground screen where everything is copied from the source prompt. Here, you can change the provider and then save it. 

We are planning to reduce this friction in the next few days by allowing users to change provider in an already saved prompt. I hope that will solve your problem.

**Comment by ranjancse26** [comment]
@VisargD Duplicate the prompt is not a solution. Sorry, I see a tight coupling and is creating a problem than help. When you say prompt library management, the whole prompt management itself should be designed in a highly decoupled manner. I hope you do understand the real issue with the current design.

**Comment by VisargD** [comment]
As I mentioned in my comment, we are already working on reducing the friction by allowing to change provider in an already saved prompt. That should ideally address the issue. Duplicating prompt is just a temporary workaround  that can be used if someone wants to use same prompt with different provider

**Comment by VisargD** [comment]
The underlying system of prompt library management is not tightly coupled with a provider. Its just a UI/UX restriction that we had which does not allow users to switch between different providers. But as mentioned earlier, it should be solved in the next few days

**Comment by ranjancse26** [comment]
@VisargD Any updates on this one? It's a major roadblock for our evaluation.

**Comment by VisargD** [comment]
This is live now. You can change provider in saved prompts as well now.

**Comment by ranjancse26** [comment]
@VisargD Sorry, I am not sure what updates you guys have provided as I still see the same as before. I got an error while switching the provided.

<img width="723" alt="image" src="https://github.com/Portkey-AI/gateway/assets/2565797/b5bd2e13-7257-4b9f-9394-943bc59366b2">

**Comment by vrushankportkey** [comment]
Thanks for flagging this, @ranjancse26. If you try hard refresh now, the Portkey app should get updated and you should be able to switch providers in the prompt playground. Please let me know if you're able to do that!

**Comment by ranjancse26** [comment]
@vrushankportkey I did a logout, also tried with the hard refresh too. However, the error still persists. You can log in to your account. Choose one of the existing prompt template, say Anthropic. Try to switch the provider and see the error during the LLM provider switch.

<img width="752" alt="image" src="https://github.com/Portkey-AI/gateway/assets/2565797/9f4ddfdb-b7a0-49af-9aa2-4c1f980e90a6">

**Comment by vrushankportkey** [comment]
Ok, checking this on priority. cc @sabbyasachiRPortkey will get back!

**Comment by sabbyasachiRPortkey** [comment]
Will share a release build on priority for this issue.
Will update once build is available.

**Comment by sabbyasachiRPortkey** [comment]
The fix on displaying the error screen while switching to a different AI Provider is fixed and pushed to production. Please wait  for application update option. Once done the issue should be fixed @ranjancse26 .

**Comment by vrushankportkey** [comment]
Closing this issue as the error is fixed now.
