### ISSUE TITLE
Test option on the Virtual Key Management

### ISSUE THREAD

**Issue by ranjancse26** [Portkey-AI/gateway#134]
I think it's a great idea to have a test option on the virtual key management. Let's say there are issues in setting up or configuring the virtual keys, based on the current design, the users are not able to understand or cannot confidently say they have set up the virtual keys for the LLM provider.

**Comment by ayush-portkey** [comment]
Great idea. We will look at building this very soon!

**Comment by vrushankportkey** [comment]
The Portkey app now does this - whenever you add a new virtual key, Portkey will verify that it's setup correct. Thanks for reqeusting this!
