### ISSUE TITLE
Multi-tenant Portkey Gateway

### ISSUE THREAD

**Issue by ranjancse26** [Portkey-AI/gateway#138]
Enterprise customers need a multi-tenant Portkey Gateway. Hence, I request you guys to please rethink and provide an option for the organizations to set up & configure the gateway by considering the tenants. It would be a great idea to also introduce the concept of account and subaccount management to allow the users to set up the tenant based on the subaccounts. The whole concept of a true multi-tenant system needs to be thought well and designed.

**Comment by ayush-portkey** [comment]
Hi @ranjancse26,

Portkey is built with full multi tenant support. We have sub-accounts, workspaces, collections, RBACs all built in for enterprise requirements.

Please drop an email to support@portkey.ai if you want to explore our enterprise plan.

I hope this helps. Closing this issue!
