### ISSUE TITLE
[Provider] Add Ollama models

### ISSUE THREAD

**Issue by vrushankportkey** [Portkey-AI/gateway#14]
Docs: https://github.com/jmorganca/ollama/blob/main/docs/api.md

**Comment by sajdakabir** [comment]
Hey @vrushankportkey , I would like to work on this issue. Can you assign it to me?

**Comment by vrushankportkey** [comment]
Thank you, @sajdakabir - assigned to you. We are just prepping to start accepting contributions, and will shortly add docs on how to add providers to Rubeus. 

You can join [our Discord](https://discord.gg/sDk9JaNfK8) to stay updated. 

Cheers!

**Comment by thawkins** [comment]
Any progress on this?, I use ollama to host all my local models.

**Comment by vrushankportkey** [comment]
Actively working on this! Will have it in ~1-2 weeks

**Comment by VisargD** [comment]
Continuing #184 here. Assigning this issue to @csgulati09
