### ISSUE TITLE
Detailed use-case driven cookbook samples

### ISSUE THREAD

**Issue by ranjancse26** [Portkey-AI/gateway#144]
At the moment, I only see 4 cookbook samples under [cookbook-samples](https://github.com/Portkey-AI/portkey-cookbook/tree/main/examples)

It would be a great idea to come up with the use-case driven examples demonstrating the capabilities of the portkey gateway. The more samples are better for everyone.

**Comment by ayush-portkey** [comment]
Hi @ranjancse26,

Yes we will be working on adding more cookbooks. If you are looking at anything specific please let us know - happy to add and share that quickly.

**Comment by ranjancse26** [comment]
@ayush-portkey The Open AI cookbook is the mother of all :)

[openai-cookbook](https://github.com/openai/openai-cookbook/tree/main/examples)

**Comment by vrushankportkey** [comment]
Thanks for the nudge, @ranjancse26. We are adding more cookbooks now!
