### ISSUE TITLE
Load balancing between two LLM providers

### ISSUE THREAD

**Issue by nlpravi** [Portkey-AI/gateway#161]
This config from the documentation is not working. I think the new API expects provider name and API key for each target instead of just the virtual key. 

{
  "strategy": {
      "mode": "loadbalance",
  },
  "targets": [
    {
      "virtualKey": "openai-virtual-key",
      "weight": 0.7
    },
    {
      "virtualKey": "azure-virtual-key",
      "weight": 0.3
    }
  ]
}

**Comment by VisargD** [comment]
The key name is virtual_key and not virtualKey. Can you please try with that? Also, can you please point us to the docs where you got this example. We will fix it there too.

**Comment by nlpravi** [comment]
Thank you. Here is the link https://portkey.ai/docs/product/ai-gateway-streamline-llm-integrations/canary-testing

**Comment by vrushankportkey** [comment]
Thank you for pointing this out, @nlpravi. Fixed the docs!
