### ISSUE TITLE
Issue with the duplication of prompts

### ISSUE THREAD

**Issue by ranjancse26** [Portkey-AI/gateway#177]
I have noticed a major issue with the duplication of the prompts. Here are the steps to reproduce.

1. Duplicate a prompt
2. Update the LLM provider by switching the model
3. Notice the prompt template is resetting to empty.

**Comment by vrushankportkey** [comment]
Hi @ranjancse26, the text sets to empty only when there is a switch from chat to text or text to chat model — for example, if you switch from GPT-3.5-Turbo (OpenAI) to Claude-2 (Anthropic), the text would set to empty, but switching to Llama 2 (Anyscale) should retain the text.

This is intended, though I totally get why it seems confusing. We should relook!

**Comment by roh26it** [comment]
Is there a case for switching between chat and text models?

**Comment by ranjancse26** [comment]
@roh26it Technically speaking, nobody cares whether it's a chat or a text based model (as nothing is enforced on the UI). Being a developer too, although I knew about the chat completion and text completion aspects, I had no idea until @vrushankportkey mentioned it. In either of the cases, we need to handle things in a much better, smarter manner.

**Comment by roh26it** [comment]
Hmm, I agree with you that there's probably a better way to handle this transition. 

Would it mean automatically converting a chat prompt into a text prompt when a text completion model is chosen?


We do this internally on the gateway. Could be done on the UI as well. 

Jfyi though, going back to a chat model will bring all of the prompt back as we do store it locally.

**Comment by ranjancse26** [comment]
@roh26it I apologize for the misunderstanding as the UI behavior was different especially when we are dealing with the Open AI vs Azure Open AI based models.

Here's what I see for the Open AI - Notice there is a clear segregation for the Chat vs Text 

<img width="165" alt="image" src="https://github.com/Portkey-AI/gateway/assets/2565797/d5857762-fd1d-4eaa-b70a-481135b8424c">

However, the way how the Azure Open AI models are being setup based on the deployment mechanism, the UI is different, and I do not see an option of Chat vs Text. 

<img width="184" alt="image" src="https://github.com/Portkey-AI/gateway/assets/2565797/81bd65e3-81c0-4819-b864-ed7e72b7209e">

I believe, the fundamental behavior of these models should be the same no matter whether it's provided by the Open AI or Azure Open AI. Hence, it's more about the way how the UI needs to be redesigned for handling the Text vs Chat based mechanism. 

Considering the model aspects, things are designed as expected. It would be great to let the users aware of it and let them choose whichever they feel is right. In turn, based on their prompt use-cases.

**Comment by roh26it** [comment]
Ahh got it! The case with Azure is that every model is a separate deployment for them. In Portkey this would mean a separate virtual key. 

So, there's almost no switching possible fwik.

**Comment by ranjancse26** [comment]
@roh26it Agree, the switching is may not be possible. Essentially, there is no fundamental difference in the prompt template if you consider the text vs chat based models.

Something else I would like to bring it up. 

The current way of handling the prompt management is super tedious and confusing. Also, I still don't understand the need for coupling the prompt template with the LLM provider model. I request you to please review the following issue. Let me know your thoughts on them.

[Issue 133](https://github.com/Portkey-AI/gateway/issues/133)

**Comment by roh26it** [comment]
1. Happy to learn more on how could we make prompt management easier! Shall we do a quick call?

2. The prompt playground allows to add a provider and model for simplicity sake. You can try out the model fast. There was an issue where we could switch providers, but that's been removed now. 

As you make the API call, you can also change the model if you like. The prompt provides a convenience function if you don't want to manage the prompt and provider in your code.

We're thinking of a prompt as a complete function that you can call using the simplest API and hence the design choices. 

I'm eager to learn more on how we could improve the UX if you have suggestions!
