### ISSUE TITLE
Feature - GuardRails for LLM

### ISSUE THREAD

**Issue by ranjancse26** [Portkey-AI/gateway#178]
This one is a feature request.

GuardRails are the most fundamental and the important one in the world of LLM. Hence, a necessary adjustment needs to be done in the library or the gateway to extend/integrate or build something with the plug and play manner to safeguard the LLM responses. 

Please refer to below ones for inspiration

[GuardRailsAI](https://www.guardrailsai.com/)
[Ensuring LLM Safety for Production Applications](https://youtu.be/NCe34tsVu0k)

**Comment by vrushankportkey** [comment]
Great suggestion! Thank you so much - tracking it at #179

**Comment by quhjih-duhkin-dywpU0** [comment]
![Uploading 06.png 800×1.734 pixels.png…]()
