### ISSUE TITLE
Ollama Integration

### ISSUE THREAD

**Issue by csgulati09** [Portkey-AI/gateway#184]
Working on integration of Ollama as a provider. 
https://ollama.ai

Following the API docs from: https://github.com/ollama/ollama/blob/main/docs/api.md

They provide with completion, chat and embeddings

Ollama endpoint have been mapped in the following ways to match our endpoint

1. api/generate -> /completions
2. api/chat -> /chat/completions
3. api/embeddings -> /embeddings

**Comment by VisargD** [comment]
Continuing this discussion in #14
