### ISSUE TITLE
clearing cache

### ISSUE THREAD

**Issue by nlpravi** [Portkey-AI/gateway#199]
How do I clear the whole cache? or reset cache for a specific entity?

Thank you, 
Ravi.

**Comment by roh26it** [comment]
This might help - https://portkey.ai/docs/product/ai-gateway-streamline-llm-integrations/cache-simple-and-semantic#force-refresh-cache

**Comment by vrushankportkey** [comment]
Hi @nlpravi closing this issue. Please feel free to reopen it if needed.
