### ISSUE TITLE
Support Anyscale Endpoints

### ISSUE THREAD

**Issue by roh26it** [Portkey-AI/gateway#2]
Anyscale launched an OpenAI compatible API for open source model hosting.

https://app.endpoints.anyscale.com/

This allows us to support the following models:

<img width="889" alt="image" src="https://github.com/Portkey-AI/Rubeus/assets/971978/f17b1a6f-d591-4517-89d6-80e117f217db">

**Comment by vrushankportkey** [comment]
#8
