### ISSUE TITLE
fix: respect cache max age from configs

### ISSUE THREAD

**Issue by VisargD** [Portkey-AI/gateway#201]
Problem:

max_age passed in configs is not getting respected. Due to this, the sent max age is not applied to cache sometimes.

Example config:
```json
{
    "cache": {"mode": "simple", "max_age": 60}
}
```

Using the above config, cache should be expired after 60 seconds.

**Comment by vrushankportkey** [comment]
Should it be `max_age`?

**Comment by VisargD** [comment]
Yes. Fixed the example.
