### ISSUE TITLE
Enhancement: Support content array input message for anthropic messages

### ISSUE THREAD

**Issue by VisargD** [Portkey-AI/gateway#244]
Anthropic now supports vision input with the release of claude-3 models. With this release, it has started accepting a different format for messages where content of a message can be an array and that array can have text and image inputs.

```
"messages": [
        {
            "role": "system",
            "content": "Your are a helpful assistant"
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "Whats in the image"
                },
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "base64data"
                    }
                }
            ]
        }
    ]
```

The system message transformer written for anthropic and bedrock-anthropic chat completions only accepts the content as a string and not as an array. This should be changed now to support array as well so that the structure is uniform for all types of messages. Here is an example of system message which should also be supported in gateway:

```
"messages": [
        {
            "role": "system",
            "content": [
                {
                    "type": "text",
                    "text": "Whats in the image"
                }
            ]
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "Whats in the image"
                },
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "base64data"
                    }
                }
            ]
        }
    ]
```

API DOCs reference for the new messages structure: https://docs.anthropic.com/claude/reference/messages_post

**Comment by flexchar** [comment]
Thank you for this, Visarg! Do you have anything against migrating to the new 'messages API` from Claude?
