### ISSUE TITLE
Missing `Makefile`?

### ISSUE THREAD

**Issue by flexchar** [Portkey-AI/gateway#261]
### What Happened?

My editor uses different formatting which is a deal breaker for PRs.

I see contributing guide mentions make commands but there's no makefile - forgot to commit?
https://github.com/Portkey-AI/gateway/blob/main/CONTRIBUTING.md#-raising-prs

---

I also see it has `prettier` dependancy. I use prettier myself. It'd be a good idea to add `prettier.config.mjs` so that one doesn't need to worry about formatting.

**Comment by VisargD** [comment]
Hey @flexchar - prettier config is on our list for sometime but we are not able to pick it up due to constant open PRs and the conflicts that it would create during the first merge. Do you have any standard prettier config that you prefer? I can check that and make any other required changes on top of it.

**Comment by flexchar** [comment]
I would love to, Visarg. Please see the PR.

The gateway has been a life changer for me, I am very grateful for you open sourcing it. Yesterday I implemented Google Vertex-AI proxy and would love to submit PR for that but it's blocked to ugly formatting mismatch.

**Comment by VisargD** [comment]
Thanks for the PR! Do you mind if I just copy the prettier config and setup in an another PR that we are working on which also has some eslint and cleanup related changes? It will reduce our review and testing time as well.

**Comment by flexchar** [comment]
Whatever helps you move faster!

**Comment by VisargD** [comment]
Thanks. I will raise a separate PR and add you as a co author for the prettier commit.

**Comment by VisargD** [comment]
Hey @flexchar - I will need your email associated with this github account to add you as a co author. Or else I can just add your username and github url. But that might not link your account to the commit.

**Comment by flexchar** [comment]
It's absolutely okay to not add me either. You've done the real work here, so don't worry about it.

I'm looking forward to integrating Vertex AI when you're ready with refactoring.That will bring the true value to the community. :)

**Comment by VisargD** [comment]
Hey. This is done now. Have added a prettier setup as well as a github action to check formatting for a PR. Thanks for the patience!
