### ISSUE TITLE
Portkey for Self Hosted LLMs in a VM?

### ISSUE THREAD

**Issue by AIAnytime** [Portkey-AI/gateway#300]
### What Happened?

Is Portkey compatible with a self hosted LLM running on a VM. I can't use Mistral API from Mistral Cloud or anywhere else?

**Comment by vrushankportkey** [comment]
Hi @AIAnytime you can use Portkey with a self-hosted LLM. Check out this doc - https://portkey.ai/docs/welcome/integration-guides/byollm

**Comment by vrushankportkey** [comment]
@AIAnytime closing this issue as it's resolved. Please feel free to reopen if you have any further questions!
