### ISSUE TITLE
[Feature] Support function calling with Gemini and Claude when using the OpenAI client

### ISSUE THREAD

**Issue by AWKohler** [Portkey-AI/gateway#306]
### What Would You Like to See with the Gateway?

It would be great if you could add function calling support in the OpenAI client for one or both of these models that support function calling. This would save a ton of headache and development time for systems already built around OpenAI's function calling, where these models could be drop in replacements.

### Context for your Request

I would want this feature to test and use some of the alternative premere function calling models in concert with existing code build around OpenAI's models

**Comment by vrushankportkey** [comment]
@AWKohler Tools message is now supported on the Gateway, while support for multi-turn tool call is pending. Tracking it here - #335 so I'll close this issue.
