### ISSUE TITLE
[Feature] : Add Local model provider

### ISSUE THREAD

**Issue by khursheed33** [Portkey-AI/gateway#311]
### What Would You Like to See with the Gateway?

Support of Local model, we should be able to use our local models by just passing the baseUrl in the body.

### Context for your Request

Support of Local model, we should be able to use our local models by just passing the baseUrl in the body.

### Your Twitter/LinkedIn

https://linkedin.com/in/khursheed33

**Comment by vrushankportkey** [comment]
@khursheed33 this is supported with the Gateway now! You can explore the docs for this here - https://portkey.ai/docs/welcome/integration-guides/byollm

Please let me know if this is helpful!

**Comment by vrushankportkey** [comment]
@khursheed33 I'll close this issue now, please feel free to reopen if needed!
