### ISSUE TITLE
customize the code designation

### ISSUE THREAD

**Issue by wyn20140226** [Portkey-AI/gateway#360]
### What Would You Like to See with the Gateway?

Do I have to configure virtual key, fallback, and load balancing through the console? Can't you customize the code designation?

**Comment by vrushankportkey** [comment]
@wyn20140226 - you can also attach any config JSON to your requests directly, without needing to save them on the Portkey app.

**Comment by vrushankportkey** [comment]
@wyn20140226 Virtual key feature is only available on the hosted app and not on the open source version. Whereas, you can configure fallback and loadbalance locally.

Please let me know if this helps! I'll close the issue for now, please feel free to reopen it if you have any more questions!
