### ISSUE TITLE
Locally run

### ISSUE THREAD

**Issue by wyn20140226** [Portkey-AI/gateway#361]
### What Would You Like to See with the Gateway?

Locally through the REST mode, no need to configure config UI, how to configure through the head mode, give a demo

**Comment by vrushankportkey** [comment]
@wyn20140226 You can run the Gateway locally with `npx @portkey-ai/gateway` and it will spin up a server on `http://localhost:8787/v1` where you can send your requests. 

Happy to get on a call and demo this if you'd like. We can conitnue chatting here - vrushank.v@portkey.ai
