### ISSUE TITLE
[Feature] Support Yi-Large from 01.ai

### ISSUE THREAD

**Issue by hargup** [Portkey-AI/gateway#385]
### What Would You Like to See with the Gateway?

01.ai is a chinese LLM provider with Yi-large being a 34B parameter model with capabilities close to GPT-4. Should like to see 01 as a provider in portkey-ai gateway

### Your Twitter/LinkedIn

https://x.com/hargup13

**Comment by hargup** [comment]
Should also be a good first issue.

**Comment by hargup** [comment]
Looks like there is support for 01.AI models already https://github.com/Portkey-AI/gateway/blob/main/src/providers/lingyi/api.ts

Though the API keys I got from the waitlist don't work for `lingyi` and only work for the url `api.01ww.xyz`

**Comment by vrushankportkey** [comment]
@hargup we've decided to close this. You could use combo of `provider` + `customHost` to route your requests to the working URL (`api.01ww.xyz`). Provider would be `lingyi`.

Check out this doc for an example on how to do this: https://portkey.ai/docs/integrations/llms/byollm#2-initialize-portkey-with-your-custom-url
