### ISSUE TITLE
[Provider] Amazon Bedrock

### ISSUE THREAD

**Issue by vrushankportkey** [Portkey-AI/gateway#39]

**Comment by ranjancse26** [comment]
+1

This support is highly essential.

**Comment by vrushankportkey** [comment]
@ranjancse26 we are working on this!

**Comment by rojosinalma** [comment]
@vrushankportkey is there any updates? Bedrock is listed on the official docs, making me think it's already usable.

**Comment by vrushankportkey** [comment]
Apologies for the confusion there! Bedrock has been in closed beta with select customers and we are planning to roll it out to everyone latest by this week. Will let you know here once it's live.

**Comment by rojosinalma** [comment]
Any news regarding Bedrock?

**Comment by rojosinalma** [comment]
@vrushankportkey

**Comment by VisargD** [comment]
Hey @rojosinalma - We will be raising a PR for bedrock tomorrow. So it should be available next week.

**Comment by vrushankportkey** [comment]
Hey @ranjancse26 & @rojosinalma - wanted to drop a note here that the Bedrock integration went live. You can check out the docs for that here: https://portkey.ai/docs/welcome/integration-guides/aws-bedrock

**Comment by rojosinalma** [comment]
Thanks for the notice!
