### ISSUE TITLE
[Feature] Configuring chatglm with portkey-ati Gateway in Autogen Studio: Local Provider Setup

### ISSUE THREAD

**Issue by poweryu** [Portkey-AI/gateway#396]
### What Would You Like to See with the Gateway?

I want to use chatglm in autogen studio through portkey-ati's gateway, but autogen studio cannot configure createHeaders. Can I set the provider in the local configuration of the gateway?

**Comment by vrushankportkey** [comment]
Hi @poweryu Portkey has native support for ChatGLM models. Here's the doc for it - https://portkey.ai/docs/welcome/integration-guides/zhipu

You can route to any LLM in your Autogen app, including the ChaGLM - using Portkey. Here's more on that - https://portkey.ai/docs/welcome/integration-guides/autogen#using-100-models-in-autogen-through-portkey

Let me know if this helps! Will close the issue for now, please feel free to reopen it if needed
