### ISSUE TITLE
Permission Denied Error While Using Portkey for bedrock models using langchain

### ISSUE THREAD

**Issue by Chaitanya-akaike** [Portkey-AI/gateway#440]
### What Happened?

I was trying out Bedrock models on Portkey , however I keep getting  the below error:
`PermissionDeniedError: Error code: 403 - {'error': {'message': 'bedrock error: The security token included in the request is invalid.', 'type': None, 'param': None, 'code': None}, 'provider': 'bedrock'}`
I have verified the credentials and they are working fine without port key

### What Should Have Happened?

This error should not be comming and instead the llm request must go on with status code 200

### Relevant Code Snippet

```
config = {
    "strategy": {
         "mode": "loadbalance"
    },
    "targets": [{
        "virtual_key": os.environ.get("bedrock_virtual_key"), 
        "override_params": {"model": "meta.llama3-70b-instruct-v1:0",}
        
    }]
}
portkey_headers = createHeaders(
    api_key=os.environ.get("api_key"),
    config=config
)

llm = ChatOpenAI(api_key="X", base_url=PORTKEY_GATEWAY_URL, default_headers=portkey_headers)

llm.invoke("What is the meaning of life, universe and everything?")
```
This is throwing error: `PermissionDeniedError: Error code: 403 - {'error': {'message': 'bedrock error: The security token included in the request is invalid.', 'type': None, 'param': None, 'code': None}, 'provider': 'bedrock'}`

### Your Twitter/LinkedIn

@kumaria3001

**Comment by VisargD** [comment]
Hey @Chaitanya-akaike! Few users have faced this in the past because they interchanged access key ID and secret key while creating a virtual key. Can you please double check if thats not the case here?

**Comment by Chaitanya-akaike** [comment]
Thanks for the reply, yes indeed that was the issue
