### ISSUE TITLE
README clarification: 9.9x faster than what?

### ISSUE THREAD

**Issue by elgalu** [Portkey-AI/gateway#454]
Please forgive my ignorance, what does `9.9x faster` mean? faster than what?

https://github.com/Portkey-AI/gateway/blob/fe0899bbf1a0f65f8f751aca8fca1b0a4409acb4/README.md?plain=1#L22

**Comment by vrushankportkey** [comment]
Hi @elgalu here we are benchmarking against a typical ExpressJS server (which is already considered fast) - Portkey, which is an optimized proxy for LLM workflows, performs ~9.9x times faster than if you were using an Express JS server.

In real time - the local gateway adds very minimal latency (to the tune of 5-10 milliseconds) while the hosted gateway (i.e. available on `https://api.portkey.ai/` ) typically adds 20ms latency to your requests.

Hope that answers your question!
