### ISSUE TITLE
TextCompletion does not support echo=True + logprobs>0

### ISSUE THREAD

**Issue by Manuscrit** [Portkey-AI/gateway#463]
### What Happened?

TextCompletion does not support the use of echo=True + logprobs>0 at the same time.
Because the first value of the logprobs in that case is None and not a number. Pydantic check then fails.

FYI, using OpenAI API with davinci-002.

### What Should Have Happened?

The None value is supported, Pydantic does not fail on check.

### Relevant Code Snippet

```
    response = gateway.completions.create(
        model=model,
        prompt=prompt,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
        n=n,
        echo=True,
        logprobs=1,
    )   
```

```
 def normal_create(
        self, model, prompt, stream, temperature, max_tokens, top_p, **kwargs
    ) -> TextCompletion:
        response = self.openai_client.with_raw_response.completions.create(
            model=model,
            prompt=prompt,
            stream=stream,
            temperature=temperature,
            max_tokens=max_tokens,
            top_p=top_p,
            **kwargs,
        )
        data = TextCompletion(**json.loads(response.text))
        data._headers = response.headers
        return data
```

**Comment by vrushankportkey** [comment]
Thank you for raising the issue @Manuscrit and for the detailed code snippets - we'll take up the issue and push a fix for it,

**Comment by narengogi** [comment]
Fixing this on the python-sdk @Manuscrit 
https://github.com/Portkey-AI/portkey-python-sdk/pull/186

**Comment by narengogi** [comment]
Already works on the node sdk
cc: @csgulati09

**Comment by vrushankportkey** [comment]
Done across the board, thank you so much @Manuscrit! Closing the issue as it's resolved now.
