### ISSUE TITLE
[Provider] Support for Nvidia NeMo

### ISSUE THREAD

**Issue by vrushankportkey** [Portkey-AI/gateway#495]

**Comment by narengogi** [comment]
Models hosted using Nvidia's NeMo servers expose Nvidia's Triton inference API's, we have a PR for that already (currently only for text completions, not chat completions)
https://github.com/Portkey-AI/gateway/pull/445
<img width="1478" alt="image" src="https://github.com/user-attachments/assets/66c058cc-4772-46df-b5c8-79988b4fc07a">
https://docs.nvidia.com/nemo-framework/user-guide/latest/overview.html
