### ISSUE TITLE
[Feature] Lowercase Check Plugin

### ISSUE THREAD

**Issue by siddharthsambharia-portkey** [Portkey-AI/gateway#514]
### What Would You Like to See with the Gateway?

Plugin Name: Lowercase Plugin
Plugin Description: Passes when the text is entirely in lowercase.

Here is the [Contributing Guide for Plugin](https://github.com/Portkey-AI/gateway/blob/main/plugins/Contributing.md)

**Comment by thev19** [comment]
@VisargD I would like to work on this.

**Comment by VisargD** [comment]
Sure. Assigning the issue to you. Thanks!
