### ISSUE TITLE
Using 'dns' package in 'validUrls' plugin breaks Edge Deployments

### ISSUE THREAD

**Issue by jpulec** [Portkey-AI/gateway#601]
## Description
In edge environments, like on Vercel's edge, many node APIs are not supported and cause deployments to fail. Including `dns` in the `validUrls` plugin causes this to happen.

### What Should Have Happened?

Consider a different approach for DNS based url validation, or maybe find a way to better allow the code to be tree shaken in edge environments.

**Comment by VisargD** [comment]
Hey @jpulec @noy4 - Sorry for the delay on this. We were trying to figure out a better way for cross-compatibility in general and lost track of this thread. We have removed the dns module dependency and replaced it with dns-over-http approach which should work fine in edge runtimes as well. Please let me know if you face issues with any other dependencies.
