### ISSUE TITLE
[Feature]  Improve UI Design of npx Command Box for Better Centering and Arrow Usage

### ISSUE THREAD

**Issue by Ncode-93** [Portkey-AI/gateway#686]
### What Would You Like to See with the Gateway?

The current design of the npx @portkey-ai/gateway box appears slightly misaligned. The left and right arrow (scroll indicator) could be adjusted, and the overall layout of the box could be centered better for a more balanced and visually appealing look. This would help the box use the available space more effectively, making the design more aesthetically pleasing.

### Context for your Request

**Suggested Improvements:**

Adjust the alignment of the npx command box to make sure it is centered vertically and horizontally.
Ensure that the left and right scroll arrows are better integrated into the design, so they don't appear cramped or too large for the content.
Improve spacing around the text to ensure the box doesn't feel crowded but still keeps the content visually centered.
**Visual Reference:** Please see the attached screenshot below for the current design that could be improved.
![image](https://github.com/user-attachments/assets/1bf0439b-8932-4cd3-a709-b28a4527e21a)

**Comment by Ncode-93** [comment]
Hey @alexsherstinsky I think it's a crucial fix as it forms the very first look for your service and it looks kinda odd as well.
I can fix that under the label of hacktoberfest.

**Comment by vrushankportkey** [comment]
Hi @Ncode-93, thank you for the suggestion! Unfortunately, the website code isn't open source. So this issue is not a part of Hacktoberfest.

**Comment by VisargD** [comment]
Closing this issue based on the thread history. Please reopen if necessary.
