### ISSUE TITLE
[Provider] xAI 

### ISSUE THREAD

**Issue by vrushankportkey** [Portkey-AI/gateway#693]
x.AI has an API following /chat/completions now - https://docs.x.ai/api/endpoints#chat-completions

**Comment by Akshay-66** [comment]
Can I work on this !!

**Comment by vrushankportkey** [comment]
Please go ahead! This would be amazing!!

**Comment by dhirenmathur** [comment]
Hey @Akshay-66  I tried generating an [initial LLD ](https://www.linkedin.com/posts/dhirenmathur_potpie-ai-agents-vs-llms-i-am-extremely-activity-7255607456448286720-roOC?utm_source=share&utm_medium=member_desktop) for this with potpie.ai, maybe it is helpful!

**Comment by PentesterPriyanshu** [comment]
@vrushankportkey i can do it i can you assign to me

**Comment by Akshay-66** [comment]
Great @dhirenmathur, Thanks for that. xAI haven't provided the endpoint for free (now), that's the reason for not moving. Do you have any alternative for that (like any 3rd party providing the same).

**Comment by narengogi** [comment]
@Akshay-66 are you still working on this?

**Comment by Akshay-66** [comment]
> @Akshay-66 are you still working on this?

Yes, on the end @narengogi .

**Comment by narengogi** [comment]
@Akshay-66 if you're not able to work on this, please let us know, someone else, or I can pick it up

**Comment by Akshay-66** [comment]
> @Akshay-66 if you're not able to work on this, please let us know, someone else, or I can pick it up

@narengogi 
Done with it but can you please deploy it once locally and let me know the changes.
Thank you.
