### ISSUE TITLE
Not showing model name

### ISSUE THREAD

**Issue by Mrinank-Bhowmick** [Portkey-AI/gateway#704]
### What Happened?

![image](https://github.com/user-attachments/assets/8e4fb0b6-cfe8-40af-a0af-d89ff80ecce7)

**Not showing model name when using cloudflare workers AI , but showing when using google AI**

### What Should Have Happened?

It should show `@cf/meta/llama` or something similar

### Your Twitter/LinkedIn

twitter - mrinank100

**Comment by Mrinank-Bhowmick** [comment]
I would like to work on this issue

**Comment by narengogi** [comment]
this is fixed
