### ISSUE TITLE
Novita AI Link

### ISSUE THREAD

**Issue by LeoWong53** [Portkey-AI/gateway#766]
### What Happened?

Hi I am Leo from Novita AI. I wish that you can add a link to our official website: novita.ai

**Comment by narengogi** [comment]
@LeoWong53 feel free to raise a PR where you think a link is necessary, you can raise a PR for this repository or https://github.com/portkey-ai/docs-core

**Comment by VisargD** [comment]
This was fixed in https://github.com/Portkey-AI/gateway/pull/767. Thanks!
