### ISSUE TITLE
[Feature] Gemini 2.0 Support

### ISSUE THREAD

**Issue by markwitt1** [Portkey-AI/gateway#805]
### What Would You Like to See with the Gateway?

Is there a timeline already for supporting Gemini 2.0 in Portkey. We are using Portkey and would love to use the new models

**Comment by narengogi** [comment]
Hey @markwitt1 gemini 2.0 and any newer models are supported by default in the gateway, you can use them by simply changing the `model` field
I suppose you're referring to support in the SAAS version UI. we're adding it there. But you should be able to use it from the API, and SDK right away whenever a new model is released
